### ISSUE TITLE
Data does not persist beyond current browser tab

### ISSUE THREAD

**Issue by humanitiesclinic** [frankdiox/OnsenUI-Todo-App#8]
When I quit the current tab, the tasks I added is gone. Is this how it should work, or am I missing something?

If that's how it should, can I use PouchDB to persist the data, and how can I do it? Any suggestions on what tutorials or resources I can follow?

**Comment by Arome8240** [comment]
Were you able to get an idea on how to fix it?

**Comment by frandiox** [comment]
It is supposed to be gone after the tab is closed since this is just an example app to show UI components. If you want to persist them, you can modify the `create` task function (https://github.com/frandiox/OnsenUI-Todo-App/blob/master/js/services.js#L13) to save data in localStorage or DB. Then, instead of adding fixtures during initialization, create the tasks you saved previously (https://github.com/frandiox/OnsenUI-Todo-App/blob/master/js/app.js#L19).

**Comment by Arome8240** [comment]
i tried using local storage it wouldn't store it as array can you please
put me through?

**Comment by Arome8240** [comment]
![frand](https://user-images.githubusercontent.com/53071050/88547784-18135700-d016-11ea-9b42-c390722b9ef1.PNG)
![frand1](https://user-images.githubusercontent.com/53071050/88547807-1f3a6500-d016-11ea-9353-82389c212a03.PNG)
Here's a snapshot of what I did but it still doesn't seem to work
